<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>spring-internals-lab</artifactId>
  <packaging>pom</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>spring-internals-lab</name>
  <url>http://maven.apache.org</url>

  <modules>
      <module>level1-reflection</module>
      <module>level2-proxies</module>
      <module>level3-bytecode</module>
      <module>level4-mini-di</module>
      <module>level5-aop</module>
      <module>level6-aot</module>
      <module>level7-native</module>
  </modules>

  <properties>
      <maven.compiler.release>25</maven.compiler.release>
  </properties>
</project>
